version: '3.9'

services:
  mongo_db:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes: 
      - mongo_db:/data/db

  node_api:
    container_name: node_container
    build: .
    ports: 
      - 5000:3000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000
      MONGODB_URL: mongodb://mongo_db:27017
      DB_NAME: food_database
      API_URL: api/v1
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}